server:
  port: 8077

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate.ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_SERVER_URI:localhost}:${DATABASE_SERVER_PORT:5432}/user_microservice
    username: '{cipher}ac05ad061b47dbdd7bc23dc945aedbf3b23133ad9e68779082594b1b5078130c'
    password: '{cipher}f21ee31d29795e8304c99949702ad49d76d3bd15edd5a095560656ae5cefdfc3'
  liquibase:
    enabled: true
    change-log: classpath:/db.migration/db.changelog.master.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8074}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  header: Authorization
  secret: Turaev
  expiration: 864000000