server:
  port: ${SERVER_PORT:8070}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8074}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: addresses
          uri: "lb://online-store-microservice-address"
          predicates:
            - "Path=/api/v1/adresses"
            - "Method=POST"

#        - id: storehouses
#            uri: "lb://online-store-microservice-storehouse"
#            predicates:
#              - "Path=/api/v1/storehouses/{id}"
#              - "Method=GET"
