server:
  port: ${SERVER_PORT:8070}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8074}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"