server:
  port: 8074

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8074}/eureka/